CREATE TABLE IF NOT EXISTS channel (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(2048) UNIQUE NOT NULL,
    ttl INTEGER NOT NULL,
    last_refresh TIMESTAMP NULL DEFAULT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NULL DEFAULT NULL
);

CREATE INDEX url_UNIQUE ON channel(url);
